fix/Invoke the result callback in FFI open and install functions
maidsafe/system_uri pull request #31
Opened 2017-10-04 15:17 UTC by bochaco

2017-10-05 08:55 UTC, nbaksalyar approved these changes

2017-10-05 10:03 UTC, nbaksalyar requested changes

2017-10-05 10:03 UTC, nbaksalyar commented on src/ffi.rs
> +        let res = rust_open(uri);
this should be `rust_open(uri)?` and the result for the `catch_unwind_cb` should be just `Ok(())`

2017-10-05 10:03 UTC, nbaksalyar commented on src/ffi.rs
> +        let res = rust_install(
Same thing here: it should be `rust_install(...)?` and return `Ok(())` on the last line of the function

2017-10-08 10:44 UTC, nbaksalyar approved these changes

2017-10-10 11:52 UTC, ustulation approved these changes

2017-10-10 11:53 UTC, merged